# Strings:

Strings are sequences of characters and can be used to store text of all kinds.
Note that you can concatenate strings to create a new string using the plus
sign. You can also access individual characters using square brackets and an
index. The name of the class for strings is str. You can often turn other
objects into strings.




S= "HELLO"
T= "WORLD"
U= S+T
print(U)
print(type(U))
print(U[9])
N=str(9876)
print(N[2])





